name: myenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy>=1.26.4
  - xarray>=2025.3.0
  - zarr>=3.0.4,<4.0.0
  - s3fs>=2025.2.0,<2026.0.0
  - h5netcdf>=1.6.1,<2.0.0
  - cftime>=1.6.4
  - nbqa
  - ruff
  - black
  - isort
  - nbconvert
  - pytest>=8.3.5,<9.0.0
  - pytest-cov
  - jupyter
  - mystmd
  - nodejs=18  # For mystmd CLI
  - ipywidgets>=8.1.5
  - pre-commit>=4.1.0
  - cartopy>=0.24.0
  - ipykernel>=6.29.5
  - ipython>=8.31.0
  - matplotlib>=3.10.0
  - matplotlib-inline>=0.1.7
  - nbformat>=5.10.4
  - pandas>=2.2.3
  - polars>=1.21.0
  - scipy>=1.15.1
  - dask>=2025.2.0,<2026.0.0
  - xesmf>=0.8.8,<0.9.0
  - shapely>=2.0.7,<3.0.0
  - cf-xarray>=0.10.0,<0.11.0
  - sparse>=0.15.5,<0.16.0
  - numba>=0.61.0,<0.62.0
  - jsonschema>=4.23.0,<5.0.0
  - pip
